### ISSUE TITLE
Integrate Scripts

### ISSUE THREAD

**Issue by Foggalong** [numixproject/core-demo#6]
I'd really like to have everything all in one script (and so Language) I'm not overly fussed about whether this is all in Python, Bash, or something else which is easy to use but I've overlooked. The current system is set up with JSON but if one language requires a specific format (there's a CSV version available in the commit history then I'm happy to look at alternatives for that implementation.

This isn't something that's crutial to have before initial release, but I'd like to have it given a serious look at the very least.

**Comment by bil-elmoussaoui** [comment]
I think Python is the way to go, and we can use the JSON file as a database

**Comment by Foggalong** [comment]
Yeah, honestly Python would be the preference of the two (not least because of my new found love for JSON) but I was having some problems getting the commands all working (even through the `call(command)` function) which is why I left it open to other languages.

**Comment by bil-elmoussaoui** [comment]
Just one question, what the osx & android scripts are supposed to do? i'm not that good with Bash :)

**Comment by Foggalong** [comment]
Here's a rough explanation:

Android:
``` bash
for f in *.*; do mv "$f" "${f//./_}"; done # replace all . with _
for f in *_svg*; do mv "$f" "${f//_svg/.svg}"; done # replace _svg with .svg
for f in *_sh*; do mv "$f" "${f//_sh/.sh}"; done # replace _sh with .sh
for f in `find`; do mv -v $f `echo $f | tr '[A-Z]' '[a-z]'`; done # I think lower cases everything and moves to the correct folder
for f in *.svg; do inkscape $f --without-gui --export-png="${f%.*}.png" --export-background-opacity 0.0 -w 192 -h 192; done # exports to png
rm android.sh *.svg # deletes junk files after operations
```

OSX:
```bash
#!/bin/bash
for f in *.svg; do inkscape $f --without-gui --export-png="${f%.*}.png" --export-background-opacity 0.0 -w 1024 -h 1024; done # export as png
rm osx.sh *.svg # clean up junk files

**Comment by Foggalong** [comment]
@bil-elmoussaoui any joy?

**Comment by bil-elmoussaoui** [comment]
I will open a PR in few hours

**Comment by bil-elmoussaoui** [comment]
@Foggalong What's the next step? :)

**Comment by Foggalong** [comment]
@bil-elmoussaoui Find a way to autogenerate a JSON file for all the icons currently available on Android and Linux so that I don't have to do it by hand. This gets a bit messy with symlinks though

**Comment by bil-elmoussaoui** [comment]
I think we should autogenerate the linux JSON file and then add Android icons by hand... I will see what i can do about that!
